### ISSUE TITLE
Commands cannot take the profile parameter

### ISSUE THREAD

**Issue by tymik** [CircleCI-Public/aws-code-deploy-orb#12]
**Orb Version**
2.0.0

**Describe the bug**
When there are env variables called `AWS_DEFAULT_REGION`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` altogether with same variables with prefixes and `aws-cli@1.4.0` is used with `aws-cli/setup` using a set of variables with prefix, the `push-bundle` and `deploy-bundle` commands don't pass the `--profile default` parameter by default.

I have added the following:

```

      - aws-code-deploy/push-bundle:
          arguments: --profile default
          application-name: <redacted>
          bundle-bucket: <redacted>
          bundle-key: <redacted>
      - aws-code-deploy/deploy-bundle:
          deploy-bundle-arguments: --profile default
          application-name: <redacted>
          deployment-group: <redacted>
          bundle-bucket: <redacted>
          bundle-key: <redacted>

```

and this actually works for `push-bundle`, but does not for `deploy-bundle` - the additional argument in `deploy-bundle` is not added to the `aws deploy get-deployment` that are executed within the orb's command.

**To Reproduce**

- set your environment variables: `AWS_DEFAULT_REGION`, `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY` and additional set of environment variables: `PREFIX_AWS_DEFAULT_REGION`, `PREFIX_AWS_ACCESS_KEY_ID`, `PREFIX_AWS_SECRET_ACCESS_KEY`
- ensure the latter ones have no rights to use codedeploy from the access defined with first set of variables
- set up following job:

```

  job:
    executor: aws-cli/default
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: PREFIX_AWS_ACCESS_KEY_ID
          aws-secret-access-key: PREFIX_AWS_SECRET_ACCESS_KEY
          aws-region: PREFIX_AWS_DEFAULT_REGION
      - aws-code-deploy/push-bundle:
          arguments: --profile default
          application-name: <redacted>
          bundle-bucket: <redacted>
          bundle-key: <redacted>
      - aws-code-deploy/deploy-bundle:
          deploy-bundle-arguments: --profile default
          application-name: <redacted>
          deployment-group: <redacted>
          bundle-bucket: <redacted>
          bundle-key: <redacted>

```

**Expected behavior**

As a user I expect the orb to have argument called `profile` for it's jobs and commands with default value equal to `default` in case none is given.
This gives me an ability to use different profiles in case there is a need.

**Additional context**

As `aws-cli@1.4.0` orb installs aws-cli v2 by default, all orbs that rely on aws-cli should have this profile parameter added - if this is yet not the case, please iterate through all aws orbs you develop to add this parameter.
