### ISSUE TITLE
Code deploy orb cannot find file located in S3 bucket?

### ISSUE THREAD

**Issue by paarth1995** [CircleCI-Public/aws-code-deploy-orb#17]
I am implementing a deployment using aws-code-deploy orb. My infrastructure is being implemented using terraform which consists of the following resources.

1. S3 bucket → stores the appspec.yml which is used to create the deployment.
2. VPC for networking.
3. An application Load balancer, 2 Listener Groups and 2 Target Groups. On initial deployment of infrastructure, go to EC2 → Target groups and you will see TG1 will have a healthy target associated with it but TG2 will not. It will change once we implement the Blue green deployment.
4. ECS → A cluster, service and task definition will be available.
5. CodeDeploy → CodeDeploy application and deployment group.

This is my terraform file for S3 resource :-

```
resource "aws_s3_bucket" "bucket" {
  bucket = "blue-green-cd-ls"
}

resource "aws_s3_object" "appspec" {
  bucket = aws_s3_bucket.bucket.id
  key    = "appspec.yaml"
  content = templatefile("${path.module}/appspec.yaml.tpl", {
    task_definition_arn = var.task_definition_arn
  })
}
```

Which successfuly creates the S3 bucket with the appspec.yml file in it. I am trying to create a deployment using CircleCI and my config.yml looks like this :-

```
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@3.1.3
  aws-code-deploy: circleci/aws-code-deploy@2.0.0
jobs:
  deploy:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - aws-code-deploy/deploy-bundle:
          application-name: "blue-green"
          bundle-bucket: "blue-green-cd-ls"
          bundle-key: "appspec.yaml"
          deployment-group: "blue-green-ls"
          bundle-type: "YAML"
          deployment-config: "CodeDeployDefault.ECSAllAtOnce"
workflows:
  build-and-deploy:
    jobs:
      - deploy
```

But my deployment keeps on failing with the following error :-

```
Deployment failed!
{
    "deploymentInfo": {
        "applicationName": "blue-green",
        "deploymentGroupName": "*************",
        "deploymentConfigName": "CodeDeployDefault.ECSAllAtOnce",
        "deploymentId": "d-85LKXCPMJ",
        "revision": {
            "revisionType": "S3",
            "s3Location": {
                "bucket": "blue-green-cd-ls",
                "key": "appspec.yaml.YAML",
                "bundleType": "YAML"
            }
        },
        "status": "Failed",
        "errorInformation": {
            "code": "INVALID_REVISION",
            "message": "The AppSpec file cannot be located in the specified S3 bucket. Verify your AppSpec file is present and that the name and key value pair specified for your S3 bucket are correct. The S3 bucket must be in your current region"
```

I double checked and the S3 bucket is definitely in the right region i.e. us-east-1. Anyone has any ideas what might be wrong? Thank you.
